apiVersion: apps/v1
kind: Deployment
metadata:
  name: maven-deploy

spec:
  selector:
    matchLabels:
      app: maven-k8s
  replicas: 1
  template: # template for the pods
    metadata:
      labels:
        app: maven-k8s
    spec:
      containers:
      - name: nginx
        image: muhammadadel8/muhammadadel8-maven:{{BUILD_NUMBER}}
        resources:
          requests:
             memory: 512Mi
             cpu: 0.5

---
apiVersion: v1
kind: Service
metadata:
  name: new-maven-svc


spec:
  selector:
    app: nginx-k8s
  ports:
    - name: http
      port: 8080
 

  type: ClusterIP
